### ISSUE TITLE
Configurar mensagem padrão de pull request nesse repositório

### ISSUE THREAD

**Issue by tkovs** [kdumagalhaes/crowdfunding-pp-reactjs#23]
Mensagem padrão do inStore para exemplo:

#### What is the purpose of this pull request?
...

#### How should this be manually tested?
...

#### Screenshots or example usage
...

#### Types of changes
- [ ] Refactor (non-breaking change which improves security, performance or maintainability)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

**Comment by kdumagalhaes** [comment]
done!
